"""
gen_sql.py - generates sql/ from data/*.json. Deterministic.

    python tools/gen_sql.py
"""

import json
from pathlib import Path
from argparse import ArgumentParser

# Helpers

_BIDI_MARKS = '\u200e\u200f\u202a\u202b\u202c\u202d\u202e'
_BIDI_TABLE = str.maketrans('', '', _BIDI_MARKS)

def format_coord(d: float) -> str:
    return f"{d:.7f}"

def sql_text(s: str) -> str:
    return s.translate(_BIDI_TABLE).replace("'", "''")

def write_utf8(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w", encoding="utf-8", newline="") as f:
        f.write(text)
    print(f"  {path.name:<34} {path.stat().st_size:>9,} bytes")

# Main

def main() -> None:
    parser = ArgumentParser()
    parser.add_argument(
        "--out-dir",
        default=str(Path(__file__).resolve().parent.parent),
    )
    args = parser.parse_args()
    out_dir = Path(args.out_dir)

    # Load
    print("\nLoading")
    wilayas = json.loads(
        (out_dir / "data" / "wilayas.json").read_text(encoding="utf-8")
    )
    communes = json.loads(
        (out_dir / "data" / "communes.json").read_text(encoding="utf-8")
    )
    print(f"  {len(wilayas)} wilayas, {len(communes)} communes")

    # SQL
    dialects = [
        {
            "file": "mysql.sql",
            "nvarchar": "VARCHAR(100) CHARACTER SET utf8mb4",
            "dec": "DECIMAL(10,7)",
            "nprefix": "",
            "drop": "DROP TABLE IF EXISTS commune; DROP TABLE IF EXISTS wilaya;",
        },
        {
            "file": "postgres.sql",
            "nvarchar": "VARCHAR(100)",
            "dec": "NUMERIC(10,7)",
            "nprefix": "",
            "drop": "DROP TABLE IF EXISTS commune; DROP TABLE IF EXISTS wilaya;",
        },
        {
            "file": "sqlserver.sql",
            "nvarchar": "NVARCHAR(100)",
            "dec": "DECIMAL(10,7)",
            "nprefix": "N",
            "drop": (
                "IF OBJECT_ID('commune') IS NOT NULL DROP TABLE commune;\r\n"
                "IF OBJECT_ID('wilaya') IS NOT NULL DROP TABLE wilaya;"
            ),
        },
    ]

    print("\nsql/")
    for d in dialects:
        q = d["nprefix"]
        lines: list[str] = []
        lines.append("-- Algeria: 69 wilayas and 1541 communes, decoupage of 2026.")
        lines.append("-- Generated by tools/gen_sql.py - do not edit by hand.")
        lines.append(
            "-- Reference: Journal Officiel n. 25 of 5 April 2026 "
            "(loi n. 26-06 of 4 April 2026)."
        )
        lines.append("")
        lines.append(d["drop"])
        lines.append("")
        lines.append("CREATE TABLE wilaya (")
        lines.append("    code      INT PRIMARY KEY,")
        lines.append(f"    name      {d['nvarchar']} NOT NULL,")
        lines.append(f"    name_ar   {d['nvarchar']} NOT NULL,")
        lines.append(f"    latitude  {d['dec']} NOT NULL,")
        lines.append(f"    longitude {d['dec']} NOT NULL")
        lines.append(");")
        lines.append("")
        lines.append("CREATE TABLE commune (")
        lines.append("    id          INT PRIMARY KEY,")
        lines.append(
            f"    post_code   {d['nvarchar'].replace('(100)', '(5)')} NOT NULL UNIQUE,"
        )
        lines.append(f"    name        {d['nvarchar']} NOT NULL,")
        lines.append(f"    name_ar     {d['nvarchar']} NOT NULL,")
        lines.append(f"    daira       {d['nvarchar']} NULL,")
        lines.append(f"    daira_ar    {d['nvarchar']} NULL,")
        lines.append("    wilaya_code INT NOT NULL REFERENCES wilaya (code),")
        lines.append(f"    latitude    {d['dec']} NOT NULL,")
        lines.append(f"    longitude   {d['dec']} NOT NULL")
        lines.append(");")
        lines.append("")
        lines.append(
            "INSERT INTO wilaya (code, name, name_ar, latitude, longitude) VALUES"
        )

        w_rows = [
            f"    ({w['code']}, {q}'{sql_text(w['name'])}', "
            f"{q}'{sql_text(w['name_ar'])}', "
            f"{format_coord(w['latitude'])}, {format_coord(w['longitude'])})"
            for w in wilayas
        ]
        lines.append(",\r\n".join(w_rows) + ";")
        lines.append("")

        # 1541 rows exceeds the 1000-row VALUES limit on SQL Server:
        # emit in batches of 500.
        for i in range(0, len(communes), 500):
            batch = communes[i : i + 500]
            lines.append(
                "INSERT INTO commune (id, post_code, name, name_ar, daira, "
                "daira_ar, wilaya_code, latitude, longitude) VALUES"
            )
            c_rows = []
            for c in batch:
                dr = (
                    f"{q}'{sql_text(c['daira'])}'"
                    if c.get("daira")
                    else "NULL"
                )
                da = (
                    f"{q}'{sql_text(c['daira_ar'])}'"
                    if c.get("daira_ar")
                    else "NULL"
                )
                c_rows.append(
                    f"    ({c['id']}, {q}'{c['post_code']}', "
                    f"{q}'{sql_text(c['name'])}', "
                    f"{q}'{sql_text(c['name_ar'])}', "
                    f"{dr}, {da}, "
                    f"{c['wilaya_code']}, "
                    f"{format_coord(c['latitude'])}, "
                    f"{format_coord(c['longitude'])})"
                )
            lines.append(",\r\n".join(c_rows) + ";")
            lines.append("")

        write_utf8(out_dir / "sql" / d["file"], "\r\n".join(lines) + "\r\n")

    print(f"\nBuild OK: {len(wilayas)} wilayas, {len(communes)} communes.\n")

if __name__ == "__main__":
    main()
