<#
    sql.ps1 - generates sql/ from data/*.json. Deterministic.

        pwsh tools/sql.ps1
#>
[CmdletBinding()]
param(
    [string]$OutDir = (Split-Path $PSScriptRoot -Parent)
)

$ErrorActionPreference = 'Stop'
[System.Threading.Thread]::CurrentThread.CurrentCulture = [Globalization.CultureInfo]::InvariantCulture

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------
function Format-Coord([double]$d) { $d.ToString('0.0000000', [Globalization.CultureInfo]::InvariantCulture) }
function ConvertTo-SqlText([string]$s) { $s -replace "'", "''" }

$utf8NoBom = New-Object System.Text.UTF8Encoding($false)
function Write-Utf8([string]$path, [string]$text) {
    New-Item -ItemType Directory -Force (Split-Path $path -Parent) | Out-Null
    [IO.File]::WriteAllText($path, $text, $utf8NoBom)
    Write-Host ("  {0,-34} {1,9:N0} bytes" -f (Split-Path $path -Leaf), (Get-Item $path).Length)
}

# ---------------------------------------------------------------------------
# Load
# ---------------------------------------------------------------------------
Write-Host "`nLoading"
$wilayas  = Get-Content (Join-Path $OutDir 'data/wilayas.json')  -Raw -Encoding UTF8 | ConvertFrom-Json
$communes = Get-Content (Join-Path $OutDir 'data/communes.json') -Raw -Encoding UTF8 | ConvertFrom-Json
Write-Host "  $($wilayas.Count) wilayas, $($communes.Count) communes"

# ---------------------------------------------------------------------------
# SQL
# ---------------------------------------------------------------------------
$dialects = @(
    @{ file = 'mysql.sql';     nvarchar = 'VARCHAR(100) CHARACTER SET utf8mb4'; dec = 'DECIMAL(10,7)'; nprefix = ''  ; drop = 'DROP TABLE IF EXISTS commune; DROP TABLE IF EXISTS wilaya;' }
    @{ file = 'postgres.sql';  nvarchar = 'VARCHAR(100)';                       dec = 'NUMERIC(10,7)'; nprefix = ''  ; drop = 'DROP TABLE IF EXISTS commune; DROP TABLE IF EXISTS wilaya;' }
    @{ file = 'sqlserver.sql'; nvarchar = 'NVARCHAR(100)';                      dec = 'DECIMAL(10,7)'; nprefix = 'N' ; drop = "IF OBJECT_ID('commune') IS NOT NULL DROP TABLE commune;`r`nIF OBJECT_ID('wilaya') IS NOT NULL DROP TABLE wilaya;" }
)
Write-Host "`nsql/"
foreach ($d in $dialects) {
    $q = $d.nprefix
    $s = [Text.StringBuilder]::new()
    [void]$s.AppendLine("-- Algeria: 69 wilayas and 1541 communes, decoupage of 2026.")
    [void]$s.AppendLine("-- Generated by tools/sql.ps1 - do not edit by hand.")
    [void]$s.AppendLine("-- Reference: Journal Officiel n. 25 of 5 April 2026 (loi n. 26-06 of 4 April 2026).")
    [void]$s.AppendLine()
    [void]$s.AppendLine($d.drop)
    [void]$s.AppendLine()
    [void]$s.AppendLine("CREATE TABLE wilaya (")
    [void]$s.AppendLine("    code      INT PRIMARY KEY,")
    [void]$s.AppendLine("    name      $($d.nvarchar) NOT NULL,")
    [void]$s.AppendLine("    name_ar   $($d.nvarchar) NOT NULL,")
    [void]$s.AppendLine("    latitude  $($d.dec) NOT NULL,")
    [void]$s.AppendLine("    longitude $($d.dec) NOT NULL")
    [void]$s.AppendLine(");")
    [void]$s.AppendLine()
    [void]$s.AppendLine("CREATE TABLE commune (")
    [void]$s.AppendLine("    id          INT PRIMARY KEY,")
    [void]$s.AppendLine("    post_code   $($d.nvarchar.Replace('(100)','(5)')) NOT NULL UNIQUE,")
    [void]$s.AppendLine("    name        $($d.nvarchar) NOT NULL,")
    [void]$s.AppendLine("    name_ar     $($d.nvarchar) NOT NULL,")
    [void]$s.AppendLine("    daira       $($d.nvarchar) NULL,")
    [void]$s.AppendLine("    daira_ar    $($d.nvarchar) NULL,")
    [void]$s.AppendLine("    wilaya_code INT NOT NULL REFERENCES wilaya (code),")
    [void]$s.AppendLine("    latitude    $($d.dec) NOT NULL,")
    [void]$s.AppendLine("    longitude   $($d.dec) NOT NULL")
    [void]$s.AppendLine(");")
    [void]$s.AppendLine()
    [void]$s.AppendLine("INSERT INTO wilaya (code, name, name_ar, latitude, longitude) VALUES")
    $rows = foreach ($w in $wilayas) { "    ({0}, {5}'{1}', {5}'{2}', {3}, {4})" -f $w.code, (ConvertTo-SqlText $w.name), (ConvertTo-SqlText $w.name_ar), (Format-Coord $w.latitude), (Format-Coord $w.longitude), $q }
    [void]$s.AppendLine(($rows -join ",`r`n") + ";")
    [void]$s.AppendLine()
    # 1541 rows exceeds the 1000-row VALUES limit on SQL Server: emit in batches.
    for ($i = 0; $i -lt $communes.Count; $i += 500) {
        $slice = $communes[$i..([Math]::Min($i + 499, $communes.Count - 1))]
        [void]$s.AppendLine("INSERT INTO commune (id, post_code, name, name_ar, daira, daira_ar, wilaya_code, latitude, longitude) VALUES")
        $rows = foreach ($c in $slice) {
            $dr = if ($c.daira)    { "$q'" + (ConvertTo-SqlText $c.daira) + "'" }    else { 'NULL' }
            $da = if ($c.daira_ar) { "$q'" + (ConvertTo-SqlText $c.daira_ar) + "'" } else { 'NULL' }
            "    ({0}, {7}'{1}', {7}'{2}', {7}'{3}', {8}, {9}, {4}, {5}, {6})" -f $c.id, $c.post_code, (ConvertTo-SqlText $c.name), (ConvertTo-SqlText $c.name_ar), $c.wilaya_code, (Format-Coord $c.latitude), (Format-Coord $c.longitude), $q, $dr, $da
        }
        [void]$s.AppendLine(($rows -join ",`r`n") + ";")
        [void]$s.AppendLine()
    }
    Write-Utf8 (Join-Path $OutDir "sql/$($d.file)") $s.ToString()
}

Write-Host "`nBuild OK: $($wilayas.Count) wilayas, $($communes.Count) communes.`n"
